# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 838676115b6d576a093cd4157ab8235cac55778ed2e9c1a35d4e316fa2de187b1922e5fba7f7338e1b70ed0d93a7ed7030b8c445a49afc4430ee5959ae1fb98d

test:
  secret_key_base: 6db3ff8467de61ef28b40526687c3c93ab780e138e0ba983b7deff623b8cfd0e1e191a82d09710ab4d40781e84cd49b790be767ead37c02d85c3d5ad535ecec5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
